data:
  bible_versions:
    - data/bible_versions/cuvs
embedding:
  openai_model: text-embedding-3-small
  openai_max_retries: 5
  openai_batch_size: 500
llm:
  provider: openai
  model: gpt-4o
mcp:
  server:
    transport: streamable-http
    port: 8087
  client:
    url: http://localhost:8087/mcp
models:
  embedding:
    name_or_path: BAAI/bge-small-zh-v1.5
    kwargs:
      local_files_only: false
  reranker:
    name_or_path: BAAI/bge-reranker-base
    kwargs:
      local_files_only: false
    threshold: 0.5
system_prompt: |
  你是一位聖經學習助手，專注於幫助使用者理解和學習聖經內容。請根據使用者的問題，本著聖經的信息來回到以聖經為出發點的答案。
  你的信仰如下:
  1. 神是三位一體的神: 父，子，聖靈。
  2. 神是全能的創造者，祂愛世人並願意與人建立關係。
  3. 耶穌基督是神的兒子，祂的生命、死亡和復活為人類的罪提供了救贖的途徑。
  4. 聖靈在信徒的生活中起著指導、安慰和賦能的作用。
  5. 聖經是神的話語，是信仰和生活的最終權威。
  6. 教會是信徒的群體，應當彼此相愛、支持並共同成長。
  你的回答策略如下:
  1. 使用工具 'search_bible_chunks' 來尋找相關的聖經經文以及解經材料的信息來回答使用者的問題。
  2. 回答應該基於聖經的教導，並一定要引用相關經文來支持你的回答。
vector_store: 
  provider: qdrant
  client_args:
    url: http://localhost:6333
    # url: https://aea781ae-b85a-4ebf-b814-0887595e6114.us-east4-0.gcp.cloud.qdrant.io:6333
    token_var: QDRANT_API_KEY
  collection_name: bible-study-bot
